#cloud-config
autoinstall:
  version: 1

  packages:
    - ubuntu-desktop

  snaps:
    - name: firefox
    - name: gnome-3-38-2004
    - name: gtk-common-themes
    - name: snap-store
    - name: snapd-desktop-integration

  identity:
    realname: 'Toast User'
    username: toastuser
    password: 'e417e230383c388f7af7ef47bcd89f426e6e67ee782904d2211cae7646acec933fbb834a2d05f3847bbf1d152272ccf6306534fd4d0f8e4150a4cc57a13e8922'
    hostname: toasthost # <-- Replace with a valid hostname

  
