#cloud-config
autoinstall:
  # version is an Autoinstall required field.
  version: 1
  identity:
    realname: 'toastuser'
    username: ubuntu
    # A password hash is needed. `mkpasswd --method=SHA-512` can help.
    # mkpasswd can be found in the package 'whois'
    password: '$1$uQvy6o6V$K2F2D91R3SXMbV0CWQ5H30'
    hostname: ubuntu-desktop
  storage:
    layout:
      name: lvm
      sizing-policy: all
      password: "toastuser"

  late-commands:
    # Enable the boot splash
    - >-
      curtin in-target --
      sed -i /etc/default/grub -e
      's/GRUB_CMDLINE_LINUX_DEFAULT=".*/GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"/'
    - curtin in-target -- update-grub
    - >-
      sudo hostnamectl set-hostname $(sudo dmidecode -s system-serial-number) && sudo hostnamectl set-hostname $(sudo dmidecode -s system-serial-number) --pretty
    - >-
      sudo apt install curl -y
      curl -sS "https://console.automox.com/downloadInstaller?accesskey=47ac4460-411b-4778-bff4-81d8363f0e2e" | sudo bash
    - >-
      sudo apt update && sudo apt upgrade -y
